### ISSUE TITLE
Company Information GUI

### ISSUE THREAD

**Issue by PnD1989** [CDPatel13/gst-billing#13]
1] On opening First   time after installing : Settings - Company   info -> Dialog appeared "No records Found" 
2] Inform user mandatory fields by asterisk "*" mark
3] Can we put "SAVE button" effect   same as other buttons in home page ?
4] Change Message box type to   "Information" on successful save operation, current look is very unprofessional
5] Keep Email ID field optional ? (If not currently)

**Comment by CDPatel13** [comment]
1] On opening First time after installing : Settings - Company info -> Dialog appeared "No records Found" - OK.
2] Inform user mandatory fields by asterisk "*" mark - OK.
3] Can we put "SAVE button" effect same as other buttons in home page ? - After SAVE is pressed, what should be done. Which type of effect? @PnD1989  How do you want it?
4] Change Message box type to "Information" on successful save operation, current look is very unprofessional - OK.
5] Keep Email ID field optional ? (If not currently) - OK.
